### ISSUE TITLE
Filetype in external modules does not enforce number of inputs passed

### ISSUE THREAD

**Issue by unode** [luispedro/ngless#54]
When using external modules one can specify

```
        arg1:
            atype: 'readset'
            can_gzip: true
```

which passes one (.1.fq), two (.1.fq, .2.fq), or three (.1.fq, .2.fq, .single.fq) files depending on what the caller used or produced, `fastq()`, `paired()` or `paired(singles=)`, respectively.

Current API specifies that you can add a `filetype` [annotation/constraint](http://ngless.embl.de/modules.html#functions) to have ngless pass the expected format:
```
        arg1:
            atype: 'readset'
            filetype: 'fq3'
            can_gzip: true
```

This didn't work as expected. In the example above, even though `fq3` (.1.fq, .2.fq, .single.fq) was specified ngless still passed either one, two or three `.fq` files.
